os: linux
dist: xenial
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
    - ubuntu-toolchain-r-test
    packages:
    - libdlib-dev
    - libopenblas-dev
    - g++-8
env:
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - git clone https://github.com/davisking/dlib.git
  - cd dlib
  - cmake .
  - cmake --build .
  - cd ..
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ujacksonrr3:$BINTRAY_API_KEY "https://api.bintray.com/content/jacksonrr3/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
